export const GET_LIST = "home/get_list"
export const GET_MORE = "home/get_more"
export const SHWO_TAB = "home/show_tab"
export const HIDE_TAB = "home/hide_tab"
export const GET_AUTHOR = "home/get_author"
export const CHANGE_AUTHOR = "home/change_author"
export const TOGGLE_TOP = "home/toggle_top"